@file:OptIn(org.jetbrains.kotlin.gradle.ExperimentalWasmDsl::class)

import java.util.Properties
import org.jetbrains.kotlin.gradle.dsl.JvmTarget

plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.multiplatform)
    alias(libs.plugins.kotlin.compose)
    alias(libs.plugins.jetbrains.compose)
}

val keystorePropertiesFile = rootProject.file("keystore.properties")
val keystoreProperties = Properties().apply {
    if (keystorePropertiesFile.exists()) {
        load(keystorePropertiesFile.inputStream())
    }
}

val appVersionName = "4.0.1"
val appVersionCode = 11

// Generates a small Kotlin file in commonMain with the version, git short hash
// of the current HEAD, and the unix time of this build. Consumed by the hidden
// settings dialog so the deployed binary can be identified at a glance.
val buildInfoOutputDir = layout.buildDirectory.dir("generated/buildInfo/commonMain/kotlin")
val generateBuildInfo by tasks.registering {
    outputs.dir(buildInfoOutputDir)
    // Re-run if the HEAD pointer or the version strings change. The task is
    // intentionally *not* cached across runs — we want the unix timestamp to
    // reflect the moment of this build.
    outputs.upToDateWhen { false }
    doLast {
        val gitHash = try {
            val proc = ProcessBuilder("git", "rev-parse", "--short=7", "HEAD")
                .directory(rootProject.projectDir)
                .redirectErrorStream(true)
                .start()
            proc.inputStream.bufferedReader().readText().trim().also { proc.waitFor() }
        } catch (e: Exception) {
            "unknown"
        }
        val buildUnixSeconds = System.currentTimeMillis() / 1000L
        val out = buildInfoOutputDir.get().asFile.resolve("yuku/gambaraja/kokrepot/BuildInfo.kt")
        out.parentFile.mkdirs()
        out.writeText(
            """
            // Auto-generated by the :app:generateBuildInfo Gradle task. Do not edit.
            package yuku.gambaraja.kokrepot

            object BuildInfo {
                const val VERSION_NAME: String = "$appVersionName"
                const val GIT_HASH: String = "$gitHash"
                const val BUILD_UNIX_SECONDS: Long = ${buildUnixSeconds}L
            }

            """.trimIndent()
        )
    }
}

kotlin {
    compilerOptions {
        // Silences the "expect/actual classes are in Beta" warning. We only use
        // expect/actual for the storage layer and accept the stability caveat.
        freeCompilerArgs.add("-Xexpect-actual-classes")
    }

    androidTarget {
        compilerOptions {
            jvmTarget.set(JvmTarget.JVM_17)
        }
    }

    wasmJs {
        outputModuleName = "gambar-aja-kok-repot"
        browser {
            commonWebpackConfig {
                outputFileName = "gambar-aja-kok-repot.js"
            }
        }
        binaries.executable()
    }

    // After the web distribution is assembled, rewrite the output index.html:
    //   1. Append a cache-busting query string (short git hash + unix seconds)
    //      to the APP_SCRIPT_URL constant the loader uses to fetch the main JS
    //      bundle. Webpack's hashed chunk filenames already cache-bust, but
    //      `gambar-aja-kok-repot.js` and `index.html` use fixed names — so
    //      returning users would otherwise load stale JS from the browser cache
    //      after a new deploy.
    //   2. Replace the __APP_VERSION__ / __BUILD_UNIX__ placeholders so the
    //      loading page shows which build is being served. The build time goes
    //      in as Unix seconds and is rendered in the viewer's local timezone
    //      by the loader JS — no "UTC" surprise from a server-formatted string.
    tasks.matching { it.name == "wasmJsBrowserDistribution" }.configureEach {
        doLast {
            val indexHtml = layout.buildDirectory
                .file("dist/wasmJs/productionExecutable/index.html").get().asFile
            if (!indexHtml.exists()) return@doLast

            val gitHash = try {
                val proc = ProcessBuilder("git", "rev-parse", "--short=7", "HEAD")
                    .directory(rootProject.projectDir)
                    .redirectErrorStream(true)
                    .start()
                proc.inputStream.bufferedReader().readText().trim().also { proc.waitFor() }
            } catch (e: Exception) {
                "unknown"
            }
            val buildUnixSeconds = System.currentTimeMillis() / 1000L
            val cacheBuster = "$gitHash-$buildUnixSeconds"
            val appVersion = "$appVersionName.$gitHash"

            val original = indexHtml.readText()
            val rewritten = original
                .replace(
                    "APP_SCRIPT_URL = \"gambar-aja-kok-repot.js\"",
                    "APP_SCRIPT_URL = \"gambar-aja-kok-repot.js?v=$cacheBuster\""
                )
                .replace("__APP_VERSION__", appVersion)
                .replace("__BUILD_UNIX__", buildUnixSeconds.toString())
            if (rewritten != original) {
                indexHtml.writeText(rewritten)
                println("[cacheBust] index.html -> gambar-aja-kok-repot.js?v=$cacheBuster")
                println("[version]   v$appVersion, build unix=$buildUnixSeconds")
            }
        }
    }

    sourceSets {
        commonMain {
            kotlin.srcDir(generateBuildInfo)
            dependencies {
                implementation(compose.runtime)
                implementation(compose.foundation)
                implementation(compose.material3)
                implementation(compose.materialIconsExtended)
                implementation(compose.ui)
                implementation(libs.kotlinx.coroutines.core)
                implementation(libs.kotlinx.datetime)
            }
        }
        androidMain.dependencies {
            implementation(libs.androidx.core.ktx)
            implementation(libs.androidx.lifecycle.runtime.ktx)
            implementation(libs.androidx.activity.compose)
        }
    }
}

android {
    namespace = "yuku.gambaraja.kokrepot"
    compileSdk = 35

    sourceSets["main"].manifest.srcFile("src/androidMain/AndroidManifest.xml")
    sourceSets["main"].res.srcDirs("src/androidMain/res")

    defaultConfig {
        applicationId = "yuku.gambaraja.kokrepot"
        minSdk = 29
        targetSdk = 35
        versionCode = appVersionCode
        versionName = appVersionName
    }

    signingConfigs {
        create("release") {
            storeFile = file(keystoreProperties.getProperty("storeFile", "../keystore/release.jks"))
            storePassword = keystoreProperties.getProperty("storePassword", "")
            keyAlias = keystoreProperties.getProperty("keyAlias", "")
            keyPassword = keystoreProperties.getProperty("keyPassword", "")
        }
    }

    buildTypes {
        release {
            isMinifyEnabled = true
            isShrinkResources = true
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro"
            )
            signingConfig = signingConfigs.getByName("release")
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
}
